#!/usr/bin/env python3
"""Generate study_hooks_gen.h by scanning studies/*/modules/study_hooks.decl.

Each study's study_hooks.decl uses macros to declare hooks:
    STUDY_SOURCE_HOOK(TypeName)
    STUDY_POST_HOOK(TypeName)
    STUDY_DECAY_HOOK(TypeName)

This script collects all declarations, generates the includes, and writes
src/core/study_hooks_gen.h with the combined StudySourceHooks,
StudyPostHooks, and StudyDecayHooks tuples.

Biologist workflow: create files in studies/{name}/modules/, run this
script (or let the build system run it), and rebuild. No CMake or core
file editing needed.
"""

import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def scan_study_hooks():
    """Scan all studies/*/modules/study_hooks.h files."""
    pattern = os.path.join(ROOT, "studies", "*", "modules", "study_hooks.decl")
    files = sorted(glob.glob(pattern))

    includes = []
    source_hooks = []
    post_hooks = []
    decay_hooks = []

    for path in files:
        study = os.path.basename(os.path.dirname(os.path.dirname(path)))
        with open(path) as f:
            for line in f:
                line = line.strip()
                # Collect #include lines
                if line.startswith("#include"):
                    includes.append(line)
                # Collect hook macros
                m = re.match(r"STUDY_SOURCE_HOOK\((\w+)\)", line)
                if m:
                    source_hooks.append(m.group(1))
                m = re.match(r"STUDY_POST_HOOK\((\w+)\)", line)
                if m:
                    post_hooks.append(m.group(1))
                m = re.match(r"STUDY_DECAY_HOOK\((\w+)\)", line)
                if m:
                    decay_hooks.append(m.group(1))

    return includes, source_hooks, post_hooks, decay_hooks, files


def generate(includes, source_hooks, post_hooks, decay_hooks, study_files):
    """Generate the study_hooks_gen.h header."""
    src_list = ",\n    ".join(source_hooks) if source_hooks else ""
    post_list = ",\n    ".join(post_hooks) if post_hooks else ""
    decay_list = ",\n    ".join(decay_hooks) if decay_hooks else ""

    include_block = "\n".join(includes) if includes else ""

    studies = []
    for f in study_files:
        studies.append(os.path.basename(os.path.dirname(os.path.dirname(f))))

    header = f"""// Auto-generated by gen_study_hooks.py. Do not edit.
// Studies: {', '.join(studies) if studies else 'none'}
#ifndef STUDY_HOOKS_GEN_H_
#define STUDY_HOOKS_GEN_H_

#include <tuple>

{include_block}

namespace bdm {{
namespace skibidy {{

using StudySourceHooks = std::tuple<{src_list}>;
using StudyDecayHooks  = std::tuple<{decay_list}>;
using StudyPostHooks   = std::tuple<{post_list}>;

}}  // namespace skibidy
}}  // namespace bdm

#endif  // STUDY_HOOKS_GEN_H_
"""
    return header


def main():
    includes, source_hooks, post_hooks, decay_hooks, files = scan_study_hooks()

    output_path = os.path.join(ROOT, "src", "core", "study_hooks_gen.h")
    header = generate(includes, source_hooks, post_hooks, decay_hooks, files)

    # Only write if changed (avoids unnecessary rebuilds)
    if os.path.exists(output_path):
        with open(output_path) as f:
            if f.read() == header:
                print(f"study_hooks_gen.h unchanged ({len(files)} study modules)")
                return

    with open(output_path, "w") as f:
        f.write(header)

    n = len(source_hooks) + len(post_hooks) + len(decay_hooks)
    studies = [os.path.basename(os.path.dirname(os.path.dirname(f))) for f in files]
    print(f"Generated study_hooks_gen.h: {n} hooks from {', '.join(studies) if studies else 'no studies'}")


if __name__ == "__main__":
    main()
