# Literature sources for perfusion module
perfusion_parameters:
  description: 'Literature sources validating perfusion and angiogenesis module parameters.

    '
  sources:
  - id: braverman2000
    authors: Braverman IM
    year: 2000
    title: The cutaneous microcirculation
    journal: J Investig Dermatol Symp Proc 5(1):3-9
    doi: 10.1046/j.1087-0024.2000.00010.x
    notes: 'Papillary dermis capillary density 2x reticular; hypodermis lowest. Supports per-layer perfusion profiles (papillary=1.0,
      reticular=0.6, hypodermis=0.3).

      '
  - id: singer1999
    authors: Singer AJ, Clark RAF
    year: 1999
    title: Cutaneous wound healing
    journal: N Engl J Med 341(10):738-746
    doi: 10.1056/NEJM199909023411006
    notes: 'Capillary buds begin 24-48h post-wounding; circulation established by 72h. Supports angio_delay=240 steps (~24h).

      '
  - id: johnson2014
    authors: Johnson KE, Wilgus TA
    year: 2014
    title: Vascular endothelial growth factor and angiogenesis in the regulation of cutaneous wound repair
    journal: Adv Wound Care 3(10):647-661
    doi: 10.1089/wound.2013.0517
    notes: 'VEGF levels elevated days 3-5, normalize days 7-14. Vessel density near-normal by days 14-21. Supports VEGF production
      and consumption rates.

      '
  - id: flegg2012
    authors: Flegg JA, Byrne HM, Flegg MB, McElwain DLS
    year: 2012
    title: 'Wound healing angiogenesis: the clinical implications of a simple mathematical model'
    journal: J Theor Biol 300:309-316
    doi: 10.1016/j.jtbi.2012.01.043
    notes: 'PDE model for O2 supply via diffusion and new vessel formation. Supports angio_vegf_rate parameter calibration.

      '
  - id: jesaitis2003
    authors: Jesaitis AJ, Franklin MJ, Berglund D, Sasaki M, Lord CI, Bleazard JB, et al.
    year: 2003
    title: Compromised host defense on Pseudomonas aeruginosa biofilms
    journal: J Immunol 171(8):4329-4339
    doi: 10.4049/jimmunol.171.8.4329
    notes: 'Biofilm bacteria induce frustrated phagocytosis in neutrophils. Supports neutrophil_clearance rate for biofilm
      module.

      '
  - id: gibson2018
    authors: Gibson B, Wilson DJ, Feil E, Eyre-Walker A
    year: 2018
    title: The distribution of bacterial doubling times in the wild
    journal: Proc R Soc B 285(1880):20180789
    doi: 10.1098/rspb.2018.0789
    notes: 'S. aureus in vivo doubling time 1.8h; P. aeruginosa 1.9-2.4h. Supports biofilm growth_rate parameter (~2h doubling).

      '
  - id: davis2008
    authors: Davis SC, Ricotti C, Cazzaniga A, Welsh E, Eaglstein WH, Mertz PM
    year: 2008
    title: Microscopic and physiologic evidence for biofilm-associated wound colonization in vivo
    journal: Wound Repair Regen 16(1):23-29
    doi: 10.1111/j.1524-475X.2007.00303.x
    notes: 'Biofilm-like structures observed 48h post-inoculation in porcine wound model. Supports biofilm seed_delay=480
      (~48h).

      '
